FROM mcr.microsoft.com/playwright:v1.49.0-jammy

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci
RUN npm install -g wait-on

RUN npx playwright install chromium --with-deps

COPY . .

CMD ["npx", "playwright", "test"]
